name: GameStore Deployment

on:
  push:
    branches:
      - dev
  release:
    types: [published]

jobs:
    deploy:
        env:
            TARGET_PATH: ${{ github.event_name == 'push' && '/home/miwi8421/gamestore/devgamestore.webdazur.com' || '/home/miwi8421/gamestore/gamestore.webdazur.com' }}
        runs-on: ubuntu-latest

        steps:
        - name: Add GitHub Runner IP to o2switch whitelist
          run: |
            IP="$(curl -s https://api.ipify.org | tr -d '\n' | tr -d '\r')"
            echo "Detected runner IP: $IP"
            echo "RUNNER_IP=$IP" >> $GITHUB_ENV
            curl -sm 45 \
            -H "Authorization: cpanel ${{ secrets.O2SWITCH_USER }}:${{ secrets.O2SWITCH_TOKEN }}" \
            "https://${{ secrets.O2SWITCH_SERVER }}:2083/execute/SshWhitelist/add?address=$IP&port=${{ secrets.O2SWITCH_PORT }}"
            echo "⏳ Waiting 35 seconds for firewall to apply changes..."
            sleep 35

        - name: Checkout
          uses: actions/checkout@master

        - name: Prepare WordPress Zip
          run: |
            WP_LINK=$(cat .github/workflows/wp-version-control.cfg)
            wget -O "./wordpress.zip" "$WP_LINK"

        - name: Prepare Plugins and Theme Zip
          run: zip -r wpcontent.zip plugins mu-plugins themes

        - name: Copy Zips to Server
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.GAMESTORE_SSH_HOST }}
            username: ${{ secrets.GAMESTORE_SSH_USER }}
            key: ${{ secrets.GAMESTORE_SSH_PRIVATE_KEY }}
            port: ${{ secrets.GAMESTORE_SSH_PORT }}
            source: "./wordpress.zip, ./wpcontent.zip"
            target: ${{ env.TARGET_PATH }}

        - name: Enable Maintenance Mode
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.GAMESTORE_SSH_HOST }}
            username: ${{ secrets.GAMESTORE_SSH_USER }}
            key: ${{ secrets.GAMESTORE_SSH_PRIVATE_KEY }}
            port: ${{ secrets.GAMESTORE_SSH_PORT }}
            source: ".maintenance"
            target: ${{ env.TARGET_PATH }}

        - name: Update WordPress Core
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.GAMESTORE_SSH_HOST }}
            username: ${{ secrets.GAMESTORE_SSH_USER }}
            key: ${{ secrets.GAMESTORE_SSH_PRIVATE_KEY }}
            port: ${{ secrets.GAMESTORE_SSH_PORT }}
            script: |
              find ${{ env.TARGET_PATH }} -type f -name '*.php' ! -name 'wp-config.php' -delete
              rm -r ${{ env.TARGET_PATH }}/wp-admin/ ${{ env.TARGET_PATH }}/wp-includes/
              unzip -o ${{ env.TARGET_PATH }}/wordpress.zip -d ${{ env.TARGET_PATH }}/
              mv ${{ env.TARGET_PATH }}/wordpress/* ${{ env.TARGET_PATH }}/
              rm -r ${{ env.TARGET_PATH }}/wordpress/

        - name: Update Plugins and Theme
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.GAMESTORE_SSH_HOST }}
            username: ${{ secrets.GAMESTORE_SSH_USER }}
            key: ${{ secrets.GAMESTORE_SSH_PRIVATE_KEY }}
            port: ${{ secrets.GAMESTORE_SSH_PORT }}
            script: |
              rm -rf ${{ env.TARGET_PATH }}/wp-content/plugins/
              rm -rf ${{ env.TARGET_PATH }}/wp-content/mu-plugins/
              rm -rf ${{ env.TARGET_PATH }}/wp-content/themes/
              unzip -o ${{ env.TARGET_PATH }}/wpcontent.zip -d ${{ env.TARGET_PATH }}/wp-content/

        - name: Disable Maintenance Mode and Remove Zips
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.GAMESTORE_SSH_HOST }}
            username: ${{ secrets.GAMESTORE_SSH_USER }}
            key: ${{ secrets.GAMESTORE_SSH_PRIVATE_KEY }}
            port: ${{ secrets.GAMESTORE_SSH_PORT }}
            script: |
              rm -f ${{ env.TARGET_PATH }}/.maintenance
              rm -f ${{ env.TARGET_PATH }}/wordpress.zip
              rm -f ${{ env.TARGET_PATH }}/wpcontent.zip

        - name: Remove GitHub Runner IP from o2switch whitelist
          if: always()
          run: |
            curl -sm 45 -H "Authorization: cpanel ${{ secrets.O2SWITCH_USER }}:${{ secrets.O2SWITCH_TOKEN }}" \
            "https://${{ secrets.O2SWITCH_SERVER }}:2083/execute/SshWhitelist/remove?address=$RUNNER_IP&port=${{ secrets.O2SWITCH_PORT }}&direction=in" || true

            curl -sm 45 -H "Authorization: cpanel ${{ secrets.O2SWITCH_USER }}:${{ secrets.O2SWITCH_TOKEN }}" \
            "https://${{ secrets.O2SWITCH_SERVER }}:2083/execute/SshWhitelist/remove?address=$RUNNER_IP&port=${{ secrets.O2SWITCH_PORT }}&direction=out" || true
